spring:
  application:
    name: 13SepApiGateway



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8088/eureka/

server:
  port: 8181
